### ISSUE TITLE
Physical coordinate Segment integration

### ISSUE THREAD

**Issue by lodygaw** [pleecs/PlasmaModelingToolkit.jl#1]
I think we should talk more about our new `Geometry.Segment` definition (based on physical coordinates):
```julia
struct Segment{X1, Y1, X2, Y2} end 
```

I started to work on that with renaming `Domains.Segment` to `Domains.Edge` and working on adding new `apply!()` to `zr.jl` (I decided to add a new `apply!()` in order to break as little as possible). I was thinking that the new `apply!()` could derive `Domains.Edge` from given `Geometry.Segment` and inform user about possible discretization error. Then add `Domains.Edge` to `model.bcs`  the same way as before. But I encountered two things:
- `model.domain` would need to know about physical coordinates it was initialized with. If not, it won't be able to determine how `Segment` maps into `Edge`.
- extracting `ZN` and `RN` from `model.domain` is kinda dirty currently: 
  ```julia
  ZN, RN = typeof(model.domain).parameters
  ```
  Maybe we could put these parameters somewhere for better access? 

I general I think that user should know only as much about discretization to be able to tune it. I don't think that he should be responsible for calculating `DZ` and `DR` as in `examples/coaxial-cable.jl`. Although it's discussable.

**Comment by bchaber** [comment]
The `Domain.Edge` can be constructed in the similar fashion as we add material markers to `AxisymmetricGrid.id`, see:
https://github.com/pleecs/PlasmaModelingToolkit.jl/blob/20d9347d9361fe7ec60d71b98ee99ab5f78ec268/src/geometry.jl#L11
The `AxisymmetricGrid` has the coordinates of its nodes.

Regarding the dirty way of accessing domain's parameters (`ZN` and `RN`) they should be extracted in the function definition:
```julia
function foo(domain::AxisymmetricGrid{ZN,RN}) where {ZN,RN}
  ...
end
```
or maybe I'm missing something here...

**Comment by lodygaw** [comment]
After further discussions, we decided to remove `Edge` and the whole mesh-oriented functionality from PMT. Now PMT allows for creating complete domain abstraction, being completely unaware of certain meshing needs (see [`PlasmaModelingToolkit.jl/examples`](https://github.com/pleecs/PlasmaModelingToolkit.jl/tree/master/examples)).
Changes here: f3864eb2c3b457efe6de7a911cba3ef8323eb8b9
