### ISSUE TITLE
Extend SurfaceImpedance with time-varying characteristics

### ISSUE THREAD

**Issue by lodygaw** [pleecs/PlasmaModelingToolkit.jl#10]
Add ability to define `SurfaceImpedance` with varying $\eta$ in time. 
What kind of functions we would like to have here beside sigmoid? @bchaber

**Comment by lodygaw** [comment]
Ok, but I would prefer using something like `SurfaceImpedance(::Sigmoid{A, B, τ, α})` anyways. What do you think?

**Comment by bchaber** [comment]
That should be it!

**Comment by lodygaw** [comment]
I am beginning to work on this and I started wondering if sigmoid function is correct name for a function which can be parametrized with `A, B, τ, α`? Shouldn't it be called `LogisticFunction`? Isn't sigmoid defined as $\dfrac{1}{1+e^{-x}}$ without any parameters? And logistic can be defined as $\dfrac{1}{L+e^{-k(x-x\_0)}}$, where $L$, $k$ and $x\_0$ can be derived from our parameters?

**Comment by bchaber** [comment]
OK, but I would suggest using $Q$ and $\nu$ for the completeness.
